version: '3.8'

services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  web:
    image: solodnikov/bronfood_backend:latest
    restart: always
    volumes:
      - ./deploy_in_container.py:/app/infra/deploy_in_container.py
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    command: python infra/deploy_in_container.py
    env_file:
      - ../.env

  nginx:
    image: nginx:1.23.3
    volumes:
      - ./nginx/test_nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_value:
  media_value:
