version: '3.8'

services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  web:
    build: ../
    restart: always
    volumes:
      - ./deploy_in_container.py:/app/infra/deploy_in_container.py
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    command: python infra/deploy_in_container.py
    env_file:
      - ../.env

    # ports:
    #   - "8000:8000"


  nginx:
    # образ, из которого должен быть запущен контейнер
    image: nginx:1.21.3-alpine

    # запросы с внешнего порта 80 перенаправляем на внутренний порт 80
    ports:
      - "80:80"

    volumes:
      # При сборке скопировать созданный конфиг nginx из исходной директории 
      # в контейнер и сохранить его в директорию /etc/nginx/conf.d/
      # - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../infra/nginx/default.conf:/etc/nginx/conf.d/default.conf

      # Контейнер nginx будет работать с данными, хранящиеся в томе static_value, 
      # через свою директорию /var/html/static/
      - static_value:/var/html/static/

      # Данные, хранящиеся в томе media_value, будут доступны в контейнере nginx
      # через директорию /var/html/media/
      - media_value:/var/html/media/

    depends_on:
      # Контейнер nginx должен быть запущен после контейнера web
      - web

volumes:
  postgres_data:
  static_value:
  media_value:
