# Generated by Django 4.2.7 on 2024-03-31 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Дополнение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Дополнение',
                'verbose_name_plural': 'Дополнения',
            },
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('coocking_time', models.PositiveIntegerField(default=1, verbose_name='Время приготовления')),
                ('image', models.ImageField(upload_to='pics', verbose_name='Изображение блюда')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='L', max_length=2, verbose_name='Размер блюда')),
                ('complement', models.ManyToManyField(to='restaurants.complement', verbose_name='Дополнения')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Категория меню')),
                ('dishes', models.ManyToManyField(to='restaurants.dish', verbose_name='Блюда')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ShopingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopingcarts', to='restaurants.dish', verbose_name='Блюдо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopingcarts', to='client.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Блюдо в корзине',
                'verbose_name_plural': 'Блюда в корзине',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='pics', verbose_name='Изображение ресторана')),
                ('begin_time', models.CharField(max_length=255, verbose_name='Начало работы')),
                ('end_time', models.CharField(max_length=255, verbose_name='Конец работы')),
                ('type_of_shop', models.CharField(choices=[('FF', 'Fastfood'), ('CA', 'Cafe'), ('CS', 'Coffeshop')], default='FF', max_length=2)),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг заведения')),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.coordinates', verbose_name='Яндекс карты координаты')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menu', verbose_name='Меню')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.tag', verbose_name='Теги')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait', models.PositiveIntegerField(default=1, verbose_name='Время ожидания')),
                ('number', models.CharField(default='NHG347', max_length=10, verbose_name='кодовый номер заказа')),
                ('price', models.PositiveIntegerField(verbose_name='Цена заказа')),
                ('is_cancel_available', models.BooleanField(default=False, verbose_name='Возможность отмены заказа')),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='restaurants.dish', verbose_name='Блюда в заказе')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='restaurants.restaurant', verbose_name='Блюдо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='client.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Избранное блюдо',
                'verbose_name_plural': 'Избранные блюда',
            },
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_shop'),
        ),
    ]
