# Generated by Django 4.2.7 on 2024-04-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('restaurants', '0002_alter_favorite_options_order_user_remove_order_meals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='restaurants.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='dish',
            field=models.ManyToManyField(related_name='shoppingcarts', to='restaurants.dish', verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcarts', to='client.client', verbose_name='Клиент'),
        ),
    ]
